# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qexp <- function(u, lambda) {
    .Call('sitmo_qexp', PACKAGE = 'sitmo', u, lambda)
}

test_sitmo <- function(n, lambda, seeds) {
    .Call('sitmo_test_sitmo', PACKAGE = 'sitmo', n, lambda, seeds)
}

