# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test Generation of a Random Exponential using sitmo and C++11
#' 
#' The function provides an implementation of creating realizations
#' an exponential 
#' 
#' @param n An \code{unsigned integer} denoting the number of realizations to generate.
#' @param lambda A \code{double} indicating the scale parameter of the distribution.
#' @param seeds A \code{vec} containing a list of seeds. Each seed is run on its own core.
#' @return A \code{vec} containing the realizations.
#' @details
#' The following function's true power is only accessible on platforms that support OpenMP (e.g. Windows and Linux).
#' However, it does provide a very good example as to how to make ones code applicable across multiple platforms.
#' 
#' With this being said, how we determine how many cores to split the generation to is governed by the number of seeds supplied.
#' In the event that one is using OS X, only the first seed supplied is used. 
#' 
#' @examples
#' a = sitmo_example(10, 5.0, c(1))
#' 
#' b = sitmo_example(10, 5.0, c(1))
#' 
#' c = sitmo_example(10, 5.0, c(2))
#' 
#' all.equal(a,b)
#' 
#' all.equal(a,c)
sitmo_example <- function(n, lambda, seeds) {
    .Call('sitmo_sitmo_example', PACKAGE = 'sitmo', n, lambda, seeds)
}

